<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Github Dashboard</h1>
    <p>Dashboard till Github.</p>
    <p>React, Serverless, AWS, RESTful</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/githubdashboard", "Github Dashboard på Github", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "http://www.1dv612.simonwebb.se/", "Demoversion av Github Dashboard", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2">
    <p>En dashboard till Github skapad med React. Backend är "Serverless" skapad med Amazon Web Services.</p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/githubdashboard.png", "Github Dashboard", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Github Dashboard</figcaption>
</figure>

</div>
</div>
