<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Konst- och Bruksglasföreningen</h1>
    <p class="lead">Konst- och Bruksglasföreningens webbplats.</p>
    <p><?php echo $this->tag->linkTo( "http://www.konstochbruksglasforeningen.se/", "Liveversion av Konst- och Bruksglasföreningen", false ); ?>.</p>
</div>

<!--<div class="col-md-6 col-md-offset-3">
    <p></p>
</div>-->

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/konstochbruksglasforeningen.png", "Konst- och Bruksglasföreningen", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Konst- och Bruksglasföreningen</figcaption>
</figure>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/konstochbruksglasforeningen_mobile.png", "Webbsidan anpassar sig efter skärmstorlek", array("class" => "img-responsive center-block") ); ?>
    <figcaption class="figure__figcaption">Webbsidan anpassar sig efter skärmstorlek</figcaption>
</figure>

</div>
</div>
