<div class="container">
<div class="row">

<div class="col-md-12">
    <h1>Konst- och Bruksglasföreningen</h1>
    <p class="lead text-center">Konst- och Bruksglasföreningens webbplats.</p>
</div>

<div class="col-md-6 col-md-offset-3">
    <p>Konst- och Bruksglasföreningens webbplats är skapad av mig.</p>
    <p>Webbplatsen finns att besöka <?php echo $this->tag->linkTo( "http://www.konstochbruksglasforeningen.se/", "http://www.konstochbruksglasforeningen.se/", false ); ?>.</p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/konstochbruksglasforeningen.png", "Konst- och Bruksglasföreningen", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Konst- och Bruksglasföreningen</figcaption>
</figure>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/konstochbruksglasforeningen_mobile.png", "Mobilanpassad", array("class" => "img-responsive center-block") ); ?>
    <figcaption class="figure__figcaption">Mobilanpassad</figcaption>
</figure>

</div>
</div>
