<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Millegården</h1>
    <p>Skyddat boende.</p>
    <p>Wordpress, PHP</p>
    <p><?php echo $this->tag->linkTo( "http://www.millegarden.se/", "Liveversion av Millegården", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2">
    <p>Millegårdens webbplats är skapad av mig.</p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/millegarden.png", "Millegården", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Millegården</figcaption>
</figure>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/millegarden_mobile.png", "Webbsidan anpassar sig efter skärmstorlek", array("class" => "img-responsive center-block") ); ?>
    <figcaption class="figure__figcaption">Webbsidan anpassar sig efter skärmstorlek</figcaption>
</figure>

</div>
</div>
