<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Monster game</h1>
    <p>Ett spel skrivet i JavaScript.</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/monstergame", "Monster game på Github", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "http://www.monstergame.simonwebb.se/", "Demoversion av Monster game", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2"></div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/monstergame.png", "Monster game", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Monster game</figcaption>
</figure>

</div>
</div>
