<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Monster game</h1>
    <p>Besegra monster och rädda dagen!</p>
    <p>JavaScript, Nodejs, Browserify</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/monstergame", "Monster game på Github", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "http://www.monstergame.simonwebb.se/", "Demoversion av Monster game", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2">
    <p>Utforska en värld fylld av monster och hemligheter. Besegra monster och samla färdigheter för att slutligen kunna besegra stora stygga <i>Snorlax</i>.</p>
    <p>Skapad med stor inspiration från Pokémonspelen.</p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/monstergame.png", "Skrämdump av Monster game", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Skärmdump av Monster game</figcaption>
</figure>

</div>
</div>
