<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>RentalMovies</h1>
    <p class="lead">Bläddra bland filmer eller hyr en film.</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/rentalmovies", "RentalMovies på Github", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "http://www.rentalmovies.simonwebb.se/", "Demoversion av RentalMovies", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2">
    <p>RentalMovies är en webbplats där besökare kan bläddra bland filmer, sortera filmer efter kategorier och "hyra" filmer.</p>
    <p>Testa gärna RentalMovies, skapa en användare, uppdatera din profil, hyr en film eller bläddra bland filmer.</p>
    <p>RentalMovies har ett administrationsverktyg som gör det möjligt att redigera och radera filmer. För att se hur administrationsverktyget fungerar går det att logga in som administratör "doe" med lösenord "doe" på demoversionen av RentalMovies.</p>
</div>

<figure class="figure col-md-6">
    <?php echo $this->tag->image( "/images/project/rentalmovies.png", "Startsida för RentalMovies", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Startsida för RentalMovies</figcaption>
</figure>

<figure class="figure col-md-6">
    <?php echo $this->tag->image( "/images/project/rentalmovies_browse_movies.png", "Bläddra bland filmer", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Bläddra bland filmer</figcaption>
</figure>

<figure class="figure col-md-6">
    <?php echo $this->tag->image( "/images/project/rentalmovies_profile.png", "Profil för en användare", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Profil för en användare</figcaption>
</figure>

<figure class="figure col-md-6">
    <?php echo $this->tag->image( "/images/project/rentalmovies_admin.png", "Redigera en filmsida", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Administrationssida</figcaption>
</figure>

</div>
</div>
