<div class="container">
<div class="row">

<div class="col-md-12">
    <h1>RentalMovies</h1>
    <p class="lead text-center">Bläddra bland filmer, hyr en film och skapa din egna profil.</p>
</div>

<div class="col-md-6 col-md-offset-3">
    <p>RentalMovies är en webbplats där besökare kan bläddra bland filmer, sortera filmer efter kategorier och "hyra" filmer.</p>
    <p>RentalMovies är skapad som ett skolprojekt.</p>
    <p>En demoversion av RentalMovies finns att se här <?php echo $this->tag->linkTo( "http://www.rentalmovies.simonwebb.se/", "http://www.rentalmovies.simonwebb.se/", false ); ?>.</p>
    <p>Testa gärna RentalMovies, skapa en användare, uppdatera din profil, hyr en film eller bläddra bland filmer.</p>
    <p>RentalMovies har ett administrationsverktyg som gör det möjligt att redigera och radera filmer. För att se hur administrationsverktyget fungerar går det att logga in som administratör "doe" med lösenord "doe" på demoversionen av RentalMovies.</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/rentalmovies", "RentalMovies på Github", false ); ?></p>
</div>

<div class="col-md-12">
<div class="row">
    <figure class="figure col-md-6">
        <?php echo $this->tag->image( "/images/rentalmovies.png", "Bläddra bland filmer", array("class" => "img-responsive") ); ?>
        <figcaption class="figure__figcaption">Startsida för RentalMovies</figcaption>
    </figure>

    <figure class="figure col-md-6">
        <?php echo $this->tag->image( "/images/rentalmovies_browse_movies.png", "Bläddra bland filmer", array("class" => "img-responsive") ); ?>
        <figcaption class="figure__figcaption">Bläddra bland filmer</figcaption>
    </figure>
</div>

<div class="row">
    <figure class="figure col-md-6">
        <?php echo $this->tag->image( "/images/rentalmovies_profile.png", "Profil för en användare", array("class" => "img-responsive") ); ?>
        <figcaption class="figure__figcaption">Profil för en användare</figcaption>
    </figure>

    <figure class="figure col-md-6">
        <?php echo $this->tag->image( "/images/rentalmovies_admin.png", "Redigera en filmsida", array("class" => "img-responsive") ); ?>
        <figcaption class="figure__figcaption">Administrationssida</figcaption>
    </figure>
</div>
</div>

</div>
</div>
