<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Simoxbook</h1>
    <p>Simoxbook är en enkel webbsida där man kan skapa en användare och delta i omröstningar.</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/simoxbook", "Simoxbook på Github", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "http://www.simoxbook.simonwebb.se/", "Demoversion av Simoxbook", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2">
    <p>Simoxbook skapades för att visa hur webbramverket <?php echo $this->tag->linkTo( "/project/simox", "Simox" ) ?> fungerar.</p>
    <p><?php echo $this->tag->linkTo( "http://www.simoxbook.simonwebb.se/poll", "Omröstningarna", false ); ?> i Simoxbook har skapats på samma sätt som i <?php echo $this->tag->linkTo( "https://vimeo.com/63022489", "Phalcons övningsvideo", false ) ?>, men skapat i mitt egna ramverk.</p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/simoxbook.png", "Simoxbook", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Simoxbook</figcaption>
</figure>

</div>
</div>
