<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Web desktop</h1>
    <p class="lead text-center">Web desktop är en skrivbordsapplikation skrivet helt i JavaScript.</p>
    <p class="text-center"><?php echo $this->tag->linkTo( "https://github.com/sios13/web-desktop", "Web desktop på Github", false ); ?></p>
    <p class="text-center"><?php echo $this->tag->linkTo( "http://www.webdesktop.simonwebb.se/", "Demoversion av Web desktop", false ); ?></p>
</div>

<div class="col-md-6 col-md-offset-3">
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/webdesktop.png", "Web desktop", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Web desktop</figcaption>
</figure>

</div>
</div>
