<div class="project container">
<div class="row">

<div class="project__header col-md-8 col-md-offset-2">
    <h1>Web desktop</h1>
    <p>Skrivbordsapplikation.</p>
    <p>JavaScript, Nodejs, Browserify, WebSockets</p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/web-desktop", "Web desktop på Github", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "http://www.webdesktop.simonwebb.se/", "Demoversion av Web desktop", false ); ?></p>
</div>

<div class="col-md-8 col-md-offset-2">
    <p>Web desktop är en skrivbordsapplikation skrivet helt i JavaScript. Öppna fönster, flytta fönster, minimera fönster, stänga fönster. Ändra inställningar, spela spel eller chatta.</p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/project/webdesktop.png", "Skärmdump av Web desktop", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Skärmdump av Web desktop</figcaption>
</figure>

</div>
</div>
