<div class="container">
<div class="row">

<div class="col-md-12">
    <h1>Web desktop</h1>
    <p class="lead text-center">Web desktop är en Windows 10 imitation skrivet helt i JavaScript.</p>
</div>

<div class="col-md-6 col-md-offset-3">
    <p>En demoversion finns att se <?php echo $this->tag->linkTo( "http://www.webdesktop.simonwebb.se/", "http://www.webdesktop.simonwebb.se/", false ); ?></p>
    <p><?php echo $this->tag->linkTo( "https://github.com/sios13/web-desktop", "Web desktop på Github", false ); ?></p>
</div>

<figure class="figure col-md-8 col-md-offset-2">
    <?php echo $this->tag->image( "/images/webdesktop.png", "Web desktop", array("class" => "img-responsive") ); ?>
    <figcaption class="figure__figcaption">Web desktop</figcaption>
</figure>

</div>
</div>
