<!DOCTYPE html>
<html lang="sv-se">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Chelsea+Market" rel="stylesheet">
        <?php echo $this->tag->stylesheetLink( "/css/normalize.css" ); ?>
        <?php echo $this->tag->stylesheetLink( "/css/bootstrap.min.css" ); ?>
        <?php echo $this->tag->stylesheetLink( "/css/highlightjs/vs2015.css" ); ?>
        <?php echo $this->tag->stylesheetLink( "/css/style.css" ); ?>
        <?php echo $this->tag->getTitle(); ?>
    </head>

    <body>
        <header class="header">
            <div class="container">
                <div class="row">
                    <div class="logo col-md-4 col-xs-10">
                        <?php echo $this->tag->linkTo( "/", "Simonwebb" ); ?>
                    </div>
                    <div class="col-md-8">
                        <ul class="menu">
                            <li class="menu__item"><?php echo $this->tag->linkTo( "/", "Hem" ); ?></li>
                            <li class="menu__item"><?php echo $this->tag->linkTo( "#myprojects", "Mina projekt", false ); ?></li>
                            <li class="menu__item"><?php echo $this->tag->linkTo( "#contact", "Kontakt", false ); ?></li>
                            <li class="menu__item"><?php echo $this->tag->linkTo( "https://github.com/sios13", "Github", false ); ?></li>
                        </ul>
                        <div class="burger">Meny</div>
                    </div>
                </div>
            </div>
        </header>

        <?php echo $this->flash->output(); ?>

        <main class="main">
            <?php echo $this->getContent(); ?>
        </main>

        <div class="projects container">
            <h2><span id="myprojects"></span>Mina projekt</h2>
            <div class="row">
                <div class="col-md-4 col-sm-6">
                    <a class="project-box" href="<?php echo $this->url->get( "/project/monstergame" ); ?>">
                        <img class="project-box__image" src="<?php echo $this->url->get( "/images/project/monstergame.png" ); ?>" alt="Monster game">
                        <div class="project-box__shadow">
                            <h3 class="project-box__title">Monster game</h3>
                            <div class="project-box__text">
                                <p>Ett spel skrivet i JavaScript!</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6">
                    <a class="project-box" href="<?php echo $this->url->get( "/project/webdesktop" ); ?>">
                        <img class="project-box__image" src="<?php echo $this->url->get( "/images/project/webdesktop.png" ); ?>" alt="Web desktop">
                        <div class="project-box__shadow">
                            <h3 class="project-box__title">Web desktop</h3>
                            <div class="project-box__text">
                                <p>Skrivbordsapplikation skrivet i JavaScript.</p>
                            </div>
                        </div>
                        <!--<a class="button button--yellow" href="<?php // echo $this->url->get( "/project/pwd" ); ?>">Läs mer</a>-->
                    </a>
                </div>
                <div class="col-md-4 col-sm-6">
                    <a class="project-box" href="<?php echo $this->url->get( "/project/simox" ); ?>">
                        <img class="project-box__image" src="<?php echo $this->url->get( "/images/project/simox.png" ); ?>" alt="Simox">
                        <div class="project-box__shadow">
                            <h3 class="project-box__title">Simox</h3>
                            <div class="project-box__text">
                                <p>Ett MVC webbramverk skrivet i PHP.</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6">
                    <a class="project-box" href="<?php echo $this->url->get( "/project/simoxbook" ); ?>">
                        <img class="project-box__image" src="<?php echo $this->url->get( "/images/project/simoxbook.png" ); ?>" alt="Simoxbook">
                        <div class="project-box__shadow">
                            <h3 class="project-box__title">Simoxbook</h3>
                            <div class="project-box__text">
                                <p>Skapa en profil och delta i omröstningar.<br>Skapad med Simox.</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6">
                    <a class="project-box" href="<?php echo $this->url->get( "/project/konstochbruksglasforeningen" ); ?>">
                        <img class="project-box__image" src="<?php echo $this->url->get( "/images/project/konstochbruksglasforeningen.png" ); ?>" alt="Konst- och Bruksglasföreningen">
                        <div class="project-box__shadow">
                            <h3 class="project-box__title">Konst- och Bruksglasföreningen</h3>
                            <div class="project-box__text">
                                <p>Webbplats om konst och glasbruk.</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6">
                    <a class="project-box" href="<?php echo $this->url->get( "/project/rentalmovies" ); ?>">
                        <img class="project-box__image" src="<?php echo $this->url->get( "/images/project/rentalmovies.png" ); ?>" alt="RentalMovies">
                        <div class="project-box__shadow">
                            <h3 class="project-box__title">RentalMovies</h3>
                            <div class="project-box__text">
                                <p>Bläddra bland filmer eller hyr en film.</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <footer class="footer container-fluid">
            <div class="row">
                <div class="text-center col-md-12">
                    <h2><span id="contact"></span>Kontakt</h2>
                    <p>Skriv mejl till mig!</p>
                    <p><a href="mailto:simon2@live.se">simon2@live.se</a></p>
                </div>
            </div>
        </footer>

        <!-- highlight.js -->
        <?php echo $this->tag->javascriptInclude( "/js/highlight.pack.js" ); ?>
        <script>hljs.initHighlightingOnLoad();</script>

        <!-- scripts -->
        <?php echo $this->tag->javascriptInclude( "/js/scripts.js" ); ?>
    </body>
</html>
